CN Translation: onchain-nft
gear-tech/wiki pull request #249
Opened 2022-08-08 10:51 UTC by liushooter

2022-08-22 07:20 UTC, xrdavies requested changes

2022-08-22 07:20 UTC, xrdavies commented on docs/examples/onchain-nft.md
> +#[derive(Debug, Encode, Decode, TypeInfo)]
这里是不是误删了？

2022-08-22 09:17 UTC, liushooter commented on docs/examples/onchain-nft.md
> +#[derive(Debug, Encode, Decode, TypeInfo)]
原文有错误，在这个pr中进行了修改
https://wiki.gear-tech.io/docs/examples/onchain-nft/

>![](https://user-images.githubusercontent.com/1235106/185886058-edb77747-5642-4b19-b763-2bd64366848d.png)

2022-09-03 07:42 UTC, xrdavies approved these changes

2022-09-03 07:42 UTC, merged