Add Validator and Nominator guide
gear-tech/wiki pull request #289
Opened 2022-10-04 15:26 UTC by EugenWay

Updated sections:

-
-
-

2022-10-07 08:36 UTC, AndrePanin requested changes
Pls add a few sentences about who are nominators, why are they needed on the network, what does it give to the nominator himself, for what and how does he receive awards. 
The same about validators - why are they needed, what functions perform, what they will get for validation etc.

2022-10-28 11:46 UTC, NikVolf commented
Please move this also to Vara-related resources

2022-10-28 13:21 UTC, AndrePanin reviewed
added some text edits. 
need to add Get Payouts part, @EugenWay

2022-10-28 13:21 UTC, AndrePanin approved these changes

2022-10-28 13:39 UTC, NikVolf requested changes
should not be on gear-tech

2022-11-02 17:12 UTC, btwiuse commented on docs/gear-networks/VARA/validator.mdx
> +wget https://github.com/gear-tech/builds/releases/download/vara/vara-nightly-linux-x86_64.tar.xz && \
download link is broken, maybe switch to https://get.gear.rs?

2022-11-23 21:48 UTC, EugenWay commented
All docs related to Vara Network was moved to https://github.com/gear-tech/vara-wiki

2022-11-23 21:48 UTC, closed without merging